#!/bin/sh

if [ -z ${COLLECTION+"true"} ]
then 
    COLLECTION="merra2"
fi
echo "COLLECTION: $COLLECTION"

if [ -z ${DAP2_CE+"true"} ]
then 
    DAP2_CE="PS"
fi
echo "DAP2_CE: $DAP2_CE"

if [ -z ${DAP_REQUEST+"true"} ]
then 
    DAP_REQUEST="dds"
fi
echo "DAP_REQUEST: $DAP_REQUEST"


BUCKET_URL="http://cloudydap.s3.amazonaws.com"

BES_CONF=$prefix/etc/bes/bes.conf
SPACE=gateway

COLLECTION_URL="$BUCKET_URL/$COLLECTION"

FILES_LIST=$COLLECTION"_AggFiles"

COLLECTION_FILE_NAMES=`cat $FILES_LIST`
      
echo "Located "`echo $COLLECTION_FILE_NAMES | wc -w `" files."

for FILE in $COLLECTION_FILE_NAMES
do
    echo "Accessing $FILE";
    S3_URL="$COLLECTION_URL/$FILE"
    ./getDAP -c $BES_CONF -s $SPACE -d $DAP_REQUEST -t "$DAP2_CE" -i $S3_URL > foo.$DAP_REQUEST
done
