#!/bin/sh

verbose=1;

export DATA_SOURCE=$1
export CLOUDYDAP_TAG="RUN_STARTED_"`date +%s`

export DAP_REQUEST=dap
export COLLECTION="merra2"
export FILES_LIST="merra2_AggFiles"
export DAP4_CE="PRECCU[0:1:0][180:1:180][288:1:288]"

export STORE_RESULT="true"



source ./aggTestProcessor
