#!/bin/sh

verbose=1;

export USE_CASE_ID=$1
if [ -z ${USE_CASE_ID+"true"} ]
then 
    USE_CASE_ID="UNKNOWN"
fi
if [ $verbose = 1 ] ; then echo "USE_CASE_ID: $USE_CASE_ID"; fi


export DATA_SOURCE="DMRPP"
if [ $verbose = 1 ] ; then echo "DATA_SOURCE: $DATA_SOURCE"; fi

export ARCH_ID="A2CFT"
if [ $verbose = 1 ] ; then echo "ARCH_ID: $ARCH_ID"; fi

export CLOUDYDAP_TAG=$USE_CASE_ID"_"$ARCH_ID"_STARTED_"`date +%s`".h5"

export DAP_REQUEST=dap
export COLLECTION="arch2/merra2"
export FILES_LIST="merra2_AggFiles"
export DAP4_CE="PRECCU[0:1:0][180:1:180][288:1:288]"

export STORE_RESULT="true"



source ./aggTestProcessor
