#!/bin/sh

verbose=1;

export USE_CASE_ID=$1
if [[ -z "${USE_CASE_ID// }" ]] || [ ! -n $USE_CASE_ID ] 
then 
    USE_CASE_ID="UNKNOWN_USE_CASE"
fi
if [ $verbose = 1 ] ; then echo "USE_CASE_ID: $USE_CASE_ID"; fi



export DATA_SOURCE="DMRPP"
if [ $verbose = 1 ] ; then echo "DATA_SOURCE: $DATA_SOURCE"; fi

export ARCH_ID="A2CFT"
if [ $verbose = 1 ] ; then echo "ARCH_ID: $ARCH_ID"; fi

export CLOUDYDAP_TAG=$USE_CASE_ID"_"$ARCH_ID"_STARTED_"`date +%s`".h5"

export DAP_REQUEST=dap
export COLLECTION="arch2/airs"
export FILES_LIST="airs_AggFiles"
export DAP4_CE="Temperature_A[0][0][0]"

export STORE_RESULT="true"

source ./aggTestProcessor



